<?php

namespace Acme\ActorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActorsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ActorsRepository extends EntityRepository
{
}
