<?php
/**
 * Created by PhpStorm.
 * User: sunshine
 * Date: 13/02/18
 * Time: 22:35
 */namespace AppBundle\Repository;
/**
 * EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $str
     * @return array|mixed
     */
    public function find($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM Actors::CLASS_ORIGIN e
                WHERE e.foo LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}